FROM openjdk:11-jdk-slim-stretch
COPY /var/lib/jenkins/workspace/Backend/backend/target/Surisuri_Masuri-0.0.1-SNAPSHOT.jar Surisuri_Masuri-0.0.1-SNAPSHOT.jar
CMD ["java", "-jar", "/Surisuri_Masuri-0.0.1-SNAPSHOT.jar"]
EXPOSE 8080